baseURL = "https://avergnaud.github.io"
languageCode = "en-us"
title = "avergnaud.github.io"
theme = "noteworthy"
paginate = 4 # Set the number of posts to show before overflowing to the next page.

[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "[Fintech](https://en.wikipedia.org/wiki/Financial_technology) and full stack development"

[taxonomies]
  tag = "tags"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1 

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "hosted-paged"
	name = "Hosted pages"
	url = "/hosted-paged/"
	weight = 3 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 4
